// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZCaC3aafsbzNFrEzAUWgmSKDfGSbJZzw',
    appId: '1:304013715770:web:21d003a114824cd9df8803',
    messagingSenderId: '304013715770',
    projectId: 'micine-1a1f0',
    authDomain: 'micine-1a1f0.firebaseapp.com',
    storageBucket: 'micine-1a1f0.firebasestorage.app',
    measurementId: 'G-C3Z37B3DD6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjgpHswEAnjY3galnLuMaiAO6jVvIdeuA',
    appId: '1:304013715770:android:f91e3d272a6d2525df8803',
    messagingSenderId: '304013715770',
    projectId: 'micine-1a1f0',
    storageBucket: 'micine-1a1f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTlr-CSNjwLQA-bkjeQlZBer7BAEWoVG8',
    appId: '1:304013715770:ios:5153956de3d4ef7edf8803',
    messagingSenderId: '304013715770',
    projectId: 'micine-1a1f0',
    storageBucket: 'micine-1a1f0.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTlr-CSNjwLQA-bkjeQlZBer7BAEWoVG8',
    appId: '1:304013715770:ios:5153956de3d4ef7edf8803',
    messagingSenderId: '304013715770',
    projectId: 'micine-1a1f0',
    storageBucket: 'micine-1a1f0.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZCaC3aafsbzNFrEzAUWgmSKDfGSbJZzw',
    appId: '1:304013715770:web:87b3af894607d4a6df8803',
    messagingSenderId: '304013715770',
    projectId: 'micine-1a1f0',
    authDomain: 'micine-1a1f0.firebaseapp.com',
    storageBucket: 'micine-1a1f0.firebasestorage.app',
    measurementId: 'G-0SN0JBCG2J',
  );
}
